#!/bin/bash
#
# 

declare -A options
options=(
  ["󰆍  Kitty"]='kitty'
  ["  Neofetch"]='kitty sh -c "neofetch" --hold'
  ["󰊗  Xournal++"]='xournalpp'
  ["  Privileged shell"]='kitty sh -c "sudo su"'
  ["  MSF Console"]='kitty sh -c "msfconsole"'
  ["  SSH - Haven"]='kitty sh -c "ssh camille@176.134.249.239 -p 7"'
  ["  Secure Chat"]='kitty sh -c "ssh camille@176.134.249.239 -p 7777"'
  ["  Airgeddon"]='kitty sh -c "sudo airgeddon"'
  ["  Evillimiter"]='kitty sh -c "sudo evillimiter"'
  ["  Tor Browser"]='torbrowser-launcher'
  )

# Build Rofi menu entries
entries=""
for app in "${!options[@]}"; do
    entries+="$app\n"
done

# Show the Rofi menu and capture the selection
selection=$(echo -e "$entries" | rofi -dmenu -theme ~/.scripts/favorites.rofi -p " Favorite Apps")

# Launch the selected app
if [ -n "$selection" ]; then
    ${options[$selection]} &
fi