#!/bin/bash
#
# 
options=(
  "󰆍  Terminal"           #0 kitty
  "  HAVEN"          #1 ~/.scripts/flex.py
  "󰊗  Prism Launcher"     #2 ~/.scripts/usb-theft 
  "  Evillimiter"        #3 sudo evillimiter
  "  MSF Console"        #4 sudo msfconsole
  "  Veracrypt"          #5 veracrypt
  "  Codium "            #6 armcord
  "  Navi"               #7 navi
  "  VirtualBox"         #8 blueman-manager
  "  Vintage Story"      #9 vintagestory
  "  Signal"             #10 signal-desktop --pasword-store=kwallet6
  "  Others"             #11 ~/.scripts/tools
  "  Favorites"          #12
  "  POWER MENU"         #13 powermenu
  )

menu_options=$(printf "%s\n" "${options[@]}")

num_options=${#options[@]}


selected=$(echo -e "$menu_options" | rofi -dmenu -p " " -l "$num_options" -theme ~/.scripts/menu.rofi)


index=-1
for i in "${!options[@]}"; do
    if [[ "${options[$i]}" == "$selected" ]]; then
        index=$i
        break
    fi
done


if [[ $index -ne -1 ]]; then
  case $index in
    0)
        /home/camille/.scripts/terminal
        ;;
    1)
        kitty -c ~/.config/kitty/ssh-kitty.conf sh -c "ssh camille@176.134.249.239 -p 7" --title "SSH - HAVEN"
        ;;
    2)
        prismlauncher &

        ;;
    3)
        kitty sh -c "clear ; sudo evillimiter"
        ;;
    4)
        kitty sh -c "clear ; sudo msfconsole"
        ;;
    5)
        #kitty sh -c "clear ; ranger"
        veracrypt
        ;;
    6)
      codium
      ;;
    7)
      kitty sh -c "navi" 2>/dev/null
      ;;
    8)
        virtualbox
        ;;
    9)
        vintagestory
        ;;
        
    10)
        signal-desktop --password-store=kwallet6
        ;;
    11)
      rofi -show drun -p " " -theme ~/.scripts/menu.rofi
        ;;
    12)
      /home/camille/.scripts/favorites
      ;;
    
    13)
      /home/camille/.scripts/powermenu
      ;;
    *)
        #notify-send "No valid option selected"
        ;;
  esac
elif [[ -n "$selected" ]]; then

  confirmation=$(echo -e " Run $selected\n󰖭 Don't run $selected" | rofi -dmenu -p " " -theme ~/.scripts/menu.rofi)

  if [[ "$confirmation" == " Run $selected" ]]; then 
    #notify-send " shell " "$selected"
    eval "$(cat /home/camille/.bashrc | grep PATH | head -n 1) ; $selected"

  fi 
fi

